apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jenkins
  namespace: jenkins
spec:
  url: https://charts.jenkins.io
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: "5.8.37"  # Ensure you're using the correct version
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: jenkins
  values:
    controller:
      ingress:
        enabled: true
        hosts:
          - host: jenkins.pbdev.pro  # Your desired Jenkins hostname
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
      admin:
        password: "admin"  # Correct value for admin password in Jenkins 5.x
      serviceType: LoadBalancer
