apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jenkins
  namespace: jenkins
spec:
  url: https://charts.jenkins.io
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: "4.0.0"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: jenkins
  values:
    controller:
      ingress:
        enabled: true
        # Define your ingress settings here
        className: "nginx"
        hosts:
          - host: jenkins.pbdev.pro
            paths:
              - path: /
                pathType: Prefix
      adminPassword: "admin"  # Change the password or use a Secret instead
      serviceType: LoadBalancer
